predicate_mapping = {
    "Created": "created",
    "HasFirstSubevent": "has first subevent",
    "HasSubevent": "has subevent",
    "CausesDesire": "causes desire",
    "InstanceOf": "instance of",
    "MotivatedByGoal": "motivated by goal",
    "DefinedAs": "defined as",
    "MadeOf": "made of",
    "Causes": "causes",
    "HasPrerequisite": "has prerequisite",
    "HasA": "has a",
    "PartOf": "part of",
    "CreatedBy": "created by",
    "Desires": "desires",
    "ReceivesAction": "receives action",
    "UsedFor": "used for",
    "DistinctFrom": "distinct from",
    "HasProperty": "has property",
    "AtLocation": "at location",
    "LocatedNear": "located near",
    "HasLastSubevent": "has last subevent",
    # Only ascent
    "CapableOf": "capable of",
    "SimilarTo": "similar to",
    "SymbolOf": "symbol of",
    "RelatedTo": "related to",
    "IsA": "is a"
}